" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    " See also http://snk.tuxfamily.org/log/vim-256color-bce.html
    set t_ut=
endif

" Switch syntax highlighting on, when the terminal has colors
if &t_Co > 2 || has("gui_running")
  syntax on
  syntax enable
endif

" Enable file type detection.
filetype plugin indent on

" Highlight trailing white spaces
match ErrorMsg '\s\+$'

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
      \ | wincmd p | diffthis
endif

" let hostname = substitute(system('hostname'), '\n', '', '')
" let current_dir = getcwd()

" Split up config settings into multiple files (modularization ftw!)
runtime! config/*

" Load any .vimrc.local files in current directory
runtime ./.vimrc.local

" Run pathogen to load plugins
execute pathogen#infect()
