" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Switch syntax highlighting on, when the terminal has colors
if &t_Co > 2 || has("gui_running")
  syntax on
  syntax enable
endif

" Enable file type detection.
filetype plugin indent on

" Highlight trailing white spaces
match ErrorMsg '\s\+$'

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
      \ | wincmd p | diffthis
endif

" let hostname = substitute(system('hostname'), '\n', '', '')
" let current_dir = getcwd()

" Set colorscheme (the first one that exists will be used)
if has#colorscheme('lucius')
    set background=dark
    colo lucius
elseif has#colorscheme('gruvbox')
    colo gruvbox
else
    colo ron
endif
" Split up config settings into multiple files (modularization ftw!)
runtime! config/*.vim

" if &term =~ 'xterm-256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    " See also http://snk.tuxfamily.org/log/vim-256color-bce.html
    " set t_ut=
" endif
set t_ut=

" Set dvorak for insert and command mode
" call ToggleDvorak(1)

" Run pathogen to load plugins
execute pathogen#infect()
execute pathogen#helptags()
